from openpyxl import Workbook, load_workbook
import os, sys, subprocess
from Application import Application

# Generate the request case ID
wbNumber = load_workbook('Applications/NewestFormNumber.xlsx')
wsNumber = wbNumber.active
AutogeneratedNumber = wsNumber['E3'].value + 1
wsNumber['E3'].value = AutogeneratedNumber
wbNumber.save('Applications/NewestFormNumber.xlsx')

# Create a new file based on the template, input the generated case ID
wb= load_workbook('Applications/FinancialRequest.xlsx')
ws = wb.active
ws['A2'].value = AutogeneratedNumber
print(ws['A2'].value)
dest_filename = 'Applications/FinancialRequest' + str(AutogeneratedNumber) + '.xlsx'
wb.save(filename = dest_filename)

# Pop up the file
opener = "open" if sys.platform == "darwin" else "xdg-open"
subprocess.call([opener, dest_filename])